apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: maven-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: dev-values.yaml

  template:
    metadata:
      name: '{{env}}-maven-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/msujith1319/sample.git
        targetRevision: main
        path: sample
        helm:
          releaseName: '{{env}}-maven-app'
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
